#+TITLE: Tree-sitter Language Bundle for Emacs

#+BEGIN_HTML
<a href="https://dev.azure.com/emacs-tree-sitter/tree-sitter-langs/_build/latest?definitionId=2&branchName=master" rel="nofollow">
  <img src="https://dev.azure.com/emacs-tree-sitter/tree-sitter-langs/_apis/build/status/ci?branchName=master&label=build&api-version=6.0-preview.1" alt="Build Status" style="max-width:100%;">
</a>
#+END_HTML

This is a convenient language bundle for the Emacs package [[https://github.com/emacs-tree-sitter/elisp-tree-sitter][tree-sitter]]. It serves as an interim distribution mechanism, until ~tree-sitter~ is widespread enough for language-specific major modes to incorporate its functionalities.

For each supported language, this package provides:
1. Pre-compiled grammar binaries for 3 major platforms: macOS, Linux and Windows, on x86_64. In the future, ~tree-sitter-langs~ may provide tooling for major modes to do this on their own.
2. An optional ~highlights.scm~ file that provides highlighting patterns. This is mainly intended for major modes that are not aware of ~tree-sitter~. A language major mode that wants to use ~tree-sitter~ for syntax highlighting should instead provide the query patterns on its own, using the mechanisms defined by [[https://ubolonton.github.io/emacs-tree-sitter/syntax-highlighting/interface-for-modes/][tree-sitter-hl]].
3. Optional query patterns for other minor modes that provide high-level functionalities on top of ~tree-sitter~, such as code folding, evil text objects... As with highlighting patterns, major modes that are directly aware of ~tree-sitter~ should provide the query patterns on their own.

** Building grammars from source
It's more convenient to work with this repository as a submodule of [[https://github.com/emacs-tree-sitter/elisp-tree-sitter#building-grammars-from-source][emacs-tree-sitter]]. However, if you want to skip that, below are the steps to build grammars from source using only this repository.

*** Tools and dependencies
- Install [[https://cask.readthedocs.io][cask]].
- Install ~npm~. (Some grammars depend on another npm-packaged grammar. For example: ~cpp~, ~typescript~.)
- Install [[https://tree-sitter.github.io/tree-sitter/creating-parsers#installation][tree-sitter CLI tool]] (if you don't use NodeJS, you can download the binary directly from [[https://github.com/tree-sitter/tree-sitter/releases][GitHub]]).
- Clone this repository and install its dependencies.
#+begin_src bash
  git clone https://github.com/emacs-tree-sitter/tree-sitter-langs
  cd tree-sitter-langs
  cask install
#+end_src

*** Building a single grammar
#+begin_src bash
  cask eval "(progn (require 'tree-sitter-langs-build) (tree-sitter-langs-compile 'rust))"
#+end_src

*** Building the whole grammar bundle
#+begin_src bash
  cask eval "(progn (require 'tree-sitter-langs-build) (tree-sitter-langs-create-bundle))"
#+end_src
