#!/usr/bin/env bash
#
# Usage:
#    compile <lang-name>
#
# Examples:
#    compile rust
#    compile cpp

set -euo pipefail

here=$(cd "$(dirname "$BASH_SOURCE")"; pwd)
PROJECT_ROOT=$(cd "$here/.."; pwd)

LANG=$1

case $LANG in
    (all)
        code="(tree-sitter-langs-create-bundle)"
        ;;
    (changed)
        code='(tree-sitter-langs-compile-changed-or-all "origin/master")'
        ;;
    (*)
        code="(tree-sitter-langs-compile '$LANG)"
esac

(

    cd "$PROJECT_ROOT"
    emacs -Q --batch \
          --directory . \
          --load tree-sitter-langs-build \
          --eval "$code"
)
