#!/usr/bin/env bash
set -euo pipefail

here=$(cd "$(dirname "$BASH_SOURCE")"; pwd)
PROJECT_ROOT=$(cd "$here/.."; pwd)

(
    cd "$PROJECT_ROOT"
    system=$(uname)

    case $system in
        (Linux)
            echo ┌─────────────────────────────────────────────────────────────────────
            echo └ Grammar binaries:
            file bin/*.so
            ldd bin/*.so
            echo ┌─────────────────────────────────────────────────────────────────────
            echo └ Emacs:
            file "$(which emacs)"
            ldd "$(which emacs)"
            ;;
        (Darwin)
            echo ┌─────────────────────────────────────────────────────────────────────
            echo └ Grammar binaries:
            file bin/*.dylib
            otool -L bin/*.dylib
            echo ┌─────────────────────────────────────────────────────────────────────
            echo └ Emacs:
            file "$(which emacs)"
            otool -L "$(which emacs)"
            ;;
        (*)
            echo "Unknown system $system"
    esac
)
