#!/usr/bin/env bash
# Print the release notes of a specific version. If a version is not explicitly specified, use the
# latest annotated tag.

set -euo pipefail

here=$(cd "$(dirname "$BASH_SOURCE")"; pwd)
PROJECT_ROOT=$(cd "$here/.."; pwd)

(
    cd "$PROJECT_ROOT"
    version=${1:-$(git describe --tags --abbrev=0)}
    emacs --batch --load script/dev.el --eval "(princ (:release-notes \"$version\"))"
)
